// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfGzezMzKir_RRjstU0bUiSkCb8pjRQWE',
    appId: '1:676616876310:web:3b8a52fd360f80f4cbe037',
    messagingSenderId: '676616876310',
    projectId: 'preorder-d773a',
    authDomain: 'preorder-d773a.firebaseapp.com',
    databaseURL: 'https://preorder-d773a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'preorder-d773a.appspot.com',
    measurementId: 'G-JMRW6EP3ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZIfqFIQcHbdBoNvvEMYlcAYS-pfO-MiA',
    appId: '1:676616876310:android:384feb8e78c3b601cbe037',
    messagingSenderId: '676616876310',
    projectId: 'preorder-d773a',
    databaseURL: 'https://preorder-d773a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'preorder-d773a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtNtqPKhkiay2zjcyQgn3oWhFsFOpcbI4',
    appId: '1:676616876310:ios:5700bcde0c084c7fcbe037',
    messagingSenderId: '676616876310',
    projectId: 'preorder-d773a',
    databaseURL: 'https://preorder-d773a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'preorder-d773a.appspot.com',
    iosClientId: '676616876310-0d2n22ccitrf77vbd4lmklppqhf75rb4.apps.googleusercontent.com',
    iosBundleId: 'com.preorder.preorder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtNtqPKhkiay2zjcyQgn3oWhFsFOpcbI4',
    appId: '1:676616876310:ios:b495087bf18cc25bcbe037',
    messagingSenderId: '676616876310',
    projectId: 'preorder-d773a',
    databaseURL: 'https://preorder-d773a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'preorder-d773a.appspot.com',
    iosClientId: '676616876310-uopk3qi6lcccc3skkk7rohd3ivd95pd3.apps.googleusercontent.com',
    iosBundleId: 'com.preorder.preorder.RunnerTests',
  );
}
